#!/usr/bin/env bash
# Emit the compose override that pins st44-home's three images to one tag.
#
# The deploy writes this file into the deploy user's home on the server and lets
# compose merge it over /srv/st44-home/infra/docker-compose.yml -- `image:` in a
# later file wins, so the host's copy can go on saying `:latest` while the stack
# runs an identifiable, rollback-able tag. That directory belongs to the server
# owner and CI cannot write it, which is why the pin arrives as an override rather
# than as an edit.
#
# CI runs this same script against infra/docker-compose.prod.yml to prove the merge
# produces the tags and keeps the server's own settings. One copy of the logic, so
# the test cannot drift from the thing it tests.
#
# Usage: generate-image-pin.sh <image-prefix> <tag>
#   generate-image-pin.sh ghcr.io/tidemann/st44-home 9f3a1c2
set -euo pipefail

prefix="${1:?image prefix, e.g. ghcr.io/tidemann/st44-home}"
tag="${2:?image tag, normally the commit sha}"

echo "# Generated by infra/generate-image-pin.sh for ${tag}. Do not edit by hand."
echo "services:"
for svc in frontend backend db; do
  printf '  %s:\n    image: %s-%s:%s\n' "$svc" "$prefix" "$svc" "$tag"
done
